### ISSUE TITLE
Recommended EC2 Instance

### ISSUE THREAD

**Issue by arikrak** [remoteinterview/compilebox#20]
What is a recommended [Amazon EC2 instance](https://aws.amazon.com/ec2/instance-types/) for running Compilebox for a low-to-medium traffic website? m3.medium works well, but what about t2.small (with burstable CPU)? Alternatively has anyone tried [Google Compute Engine](https://cloud.google.com/compute/)?

**Comment by DoctorsInTech** [comment]
Which EC2 instance did you think was best?
