### ISSUE TITLE
Internet is accessible for usercode

### ISSUE THREAD

**Issue by cacophone** [remoteinterview/compilebox#21]
[internet access](https://codepad.remoteinterview.io/internetaccess
)
```python
from urllib2 import urlopen
print urlopen('http://api.icndb.com/jokes/random').read()
```

If someone needs to disable internet access for dockers containers how he/she should go about it?

Thanks

**Comment by asadm** [comment]
You can add ``--net=none`` flag [in this line](https://github.com/remoteinterview/compilebox/blob/7586886f599615ac56fb1f7ac520aa78da932942/API/DockerSandbox.js#L134) to disable any network access to the containers.

**Comment by cacophone** [comment]
Changed [this line](https://github.com/remoteinterview/compilebox/blob/7586886f599615ac56fb1f7ac520aa78da932942/API/DockerTimeout.sh#L7) to `cont=$(docker run -d --net=none "$@")`. Worked like a charm. Thanks @asadm
