### ISSUE TITLE
Everything is returning timeout error

### ISSUE THREAD

**Issue by IAmDragon** [remoteinterview/compilebox#24]
------------------------------
ATTEMPTING TO REMOVE: temp/0a548770a09aa9346eab
------------------------------
Timed Out: temp/0a548770a09aa9346eab Python
Time:
undefined

Getting this while trying to run a python script 'print "Hello"'

Anyone know any ways of fixing this? DigitalOcean 2GB of Ram

**Comment by asadm** [comment]
Can you see if solutions from this thread #4 solves the issue for you?

**Comment by IAmDragon** [comment]
It doesn't unfortunately, I already saw it. 

If it makes a difference I'm on Ubuntu 16.04, but I imagine it works just the same as 14.04

**Comment by asadm** [comment]
I did a fresh install on 16.04 and it works fine. Let me help you debug.

First try `docker images` and see if there is an image named `virtual_machine`. If not, try running the setup script again.

**Comment by IAmDragon** [comment]
Tried it, output 
```
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
virtual_machine       latest              70badc28fadd        9 days ago          2.799 GB
chug/ubuntu14.04x64   latest              aaaa7bd9d11a        2 years ago         224.7 MB
```

**Comment by asadm** [comment]
Interesting. Can you try running the server with sudo? ie. `sudo nodejs app.js`. It might be a permission issue.

Also is the problem only for python or for all other languages too?

**Comment by IAmDragon** [comment]
All languages, and I tried sudo as well, that's what made it start to give me some output besides timed out immediately

If you'd like access to my gitlab repo to see what I have you're more than welcome to it

- Zach

**Comment by asadm** [comment]
I would actually recommend debugging the code at this point. By pausing at [this](https://github.com/remoteinterview/compilebox/blob/master/API/DockerSandbox.js#L141) line.

Few things to check:
- Is the folder `this.folder` actually created with the required files (code, stdin) in the `./temp` folder.
- Going inside the current container by `docker exec -it <id of running container> bash` and trying to run the python script yourself (`python usercode/file.py`).

Hope that helps.

**Comment by IAmDragon** [comment]
Is the folder this.folder actually created with the required files (code, stdin) in the ./temp folder
Yes, I've killed the process before
Not quite sure how to pause it, I'm running it alongside a Laravel application (which is where it receives the post from), can I pause the process without killing it?

- Zach

**Comment by asadm** [comment]
Try adding `debugger;` at that line and then running the server using `sudo nodejs debug app.js`. This will pause the program at that point. To continue type `cont`.

**Comment by IAmDragon** [comment]
Inserted a breakpoint there, seems as though no container is getting started? 

There are no active containers when I'm there
` docker info
Containers: 0
 Running: 0
 Paused: 0
 Stopped: 0
Images: 30
Server Version: 1.12.1
Storage Driver: overlay
 Backing Filesystem: extfs
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge overlay null host
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Security Options: apparmor
Kernel Version: 4.4.0-38-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 2
Total Memory: 1.953 GiB
Name: HandleySites
ID: LTCC:UUQR:JVBW:564S:FVXE:4EDN:72BZ:YWGE:VRHS:MNXS:S2QC:7CKX
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Insecure Registries:
 127.0.0.0/8
`

**Comment by asadm** [comment]
Okay let's debug the starting code then.

Change [this](https://github.com/remoteinterview/compilebox/blob/master/API/DockerSandbox.js#L140) line to: 
```
exec(st, function(error, stdout, stderr){
    console.log(error,stdout,stderr);
})
```

to see what's happening.

**Comment by IAmDragon** [comment]
{ Error: Command failed: /var/www/html/TruthfulTesting/public/API/DockerTimeout.sh 30s -u mysql -e 'NODE_PATH=/usr/local/lib/node_modules' -i -t -v  ```
"/var/www/html/TruthfulTesting/public/API/temp/35a4a2d25b9acaab6236":/usercode virtual_machine /usercode/script.sh python file.py
/bin/sh: 1: /var/www/html/TruthfulTesting/public/API/DockerTimeout.sh: Permission denied

```

**Comment by asadm** [comment]
It's likely a folder permission issue somewhere. Can you git clone compilebox to your home folder and then try running it? (no need to run install script, just the API)

**Comment by IAmDragon** [comment]
Done -- 
`------------------------------
{ Error: Command failed: /var/www/html/TruthfulTesting/public/API/DockerTimeout.sh 30s -u mysql -e 'NODE_PATH=/usr/local/lib/node_modules' -i -t -v  "/var/www/html/TruthfulTesting/public/API/temp/cdc7d4067d3933717c07":/usercode virtual_machine /usercode/script.sh python file.py

    at ChildProcess.exithandler (child_process.js:206:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
  killed: false,
  code: 1,
  signal: null,
  cmd: '/var/www/html/TruthfulTesting/public/API/DockerTimeout.sh 30s -u mysql -e \'NODE_PATH=/usr/local/lib/node_modules\' -i -t -v  "/var/www/html/TruthfulTesting/public/API/temp/cdc7d4067d3933717c07":/usercode virtual_machine /usercode/script.sh python file.py  ' } '' ''
Checking /var/www/html/TruthfulTesting/public/API/temp/cdc7d4067d3933717c07: for completion: 0
DONE
ATTEMPTING TO REMOVE: temp/cdc7d4067d3933717c07
------------------------------
Error file:

Main File
hello world
*-COMPILEBOX::ENDOFOUTPUT-* .09

Time:
 .09
`

**Comment by IAmDragon** [comment]
That fixed it!

Seems that you need to sudo chmod -R 777 /path_to_api_folder/API

I still get that error above but it doesn't seem to affect it?

**Comment by asadm** [comment]
Yes that's weird.

**Comment by IAmDragon** [comment]
Well it works, thank you for all the help, I really appreciate it!

**Comment by asadm** [comment]
Awesome!

**Comment by SantoshKumar3295** [comment]
compilebox/Setup/UpdateDocker.sh: line 3: Dockerfile: No such file or directory
Retrieving Installed Docker Images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
<none>                <none>              57d2cfcccb1e        16 hours ago        1.586 GB
chug/ubuntu14.04x64   latest              aaaa7bd9d11a        3 years ago         224.7


No Docker Image is generating i have tried the fresh install and checked the permission thing but still its not working.Please help

**Comment by SantoshKumar3295** [comment]
Creating Docker Image
compilebox/Setup/UpdateDocker.sh: line 3: Dockerfile: No such file or directory
Retrieving Installed Docker Images
REPOSITORY            TAG                 IMAGE ID            CREATED             SIZE
<none>                <none>              57d2cfcccb1e        16 hours ago        1.586 GB
chug/ubuntu14.04x64   latest              aaaa7bd9d11a        3 years ago         224.7 MB

**Comment by SantoshKumar3295** [comment]
Creating Docker Image
compilebox/Setup/UpdateDocker.sh: line 3: Dockerfile: No such file or directory
Retrieving Installed Docker Images
REPOSITORY       TAG                 IMAGE ID            CREATED             SIZE
None<none>      None<none>     57d2cfcccb1e        16 hours ago        1.586 GB
chug/ubuntu14.04x64   latest     aaaa7bd9d11a        3 years ago         224.7 MB

**Comment by pvn-chi-ngo** [comment]
Please help me!
I tried to  debug and then I met:

> { [Error: Command failed: /bin/sh -c /app/API/DockerTimeout.sh 20s -i -t -v  "/app/API/temp/d0fe1e02ae56806a1f44":/usercode virtual_machine /usercode/script.sh python file.py  
> docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \"/usercode/script.sh\": stat /usercode/script.sh: no such file or directory".
> ]
>   killed: false,
>   code: 127,
>   signal: null,
>   cmd: '/bin/sh -c /app/API/DockerTimeout.sh 20s -i -t -v  "/app/API/temp/d0fe1e02ae56806a1f44":/usercode virtual_machine /usercode/script.sh python file.py  ' } '' 'docker: Error response from daemon: oci runtime error: container_linux.go:262: starting container process caused "exec: \\"/usercode/script.sh\\": stat /usercode/script.sh: no such file or directory".\n'

**Comment by bikramjit-full-stack-developer** [comment]
I have fixed the issue by following way.

For mac
==================
#!/bin/bash
set -e

to=$1
shift

cont=$(docker run -d "$@")
code=$(gtimeout "$to" docker wait "$cont" || true)
echo -n 'status: '
if [ -z "$code" ]; then
    echo gtimeout
else
    echo exited: $code
fi

echo output:
# pipe to sed simply for pretty nice indentation
docker logs $cont | sed 's/^/\t/'

docker rm $cont &> /dev/null

For ubuntu
============

#!/bin/bash
set -e

to=$1
shift

cont=$(docker run -d "$@")
code=$(timeout "$to" docker wait "$cont" || true)
echo -n 'status: '
if [ -z "$code" ]; then
    echo timeout
else
    echo exited: $code
fi

echo output:
# pipe to sed simply for pretty nice indentation
docker logs $cont | sed 's/^/\t/'

docker rm $cont &> /dev/null

**Comment by slidenerd** [comment]
@bikramjit-full-stack-developer  inside which file on Mac did you write that shell script?

**Comment by jetma** [comment]
> @bikramjit-full-stack-developer inside which file on Mac did you write that shell script?

`DockerTimeout.sh`

**Comment by jetma** [comment]
> I have fixed the issue by following way.
> To install gtimeout
> I had the same problem on OSX. I fixed it as follows:
> 
> ```
> Installing CoreUtils
> brew install coreutil
> ```
> 
> # For mac
> #!/bin/bash
> set -e
> 
> to=$1
> shift
> 
> cont=$(docker run -d "$@")
> code=$(gtimeout "$to" docker wait "$cont" || true)
> echo -n 'status: '
> if [ -z "$code" ]; then
> echo gtimeout
> else
> echo exited: $code
> fi
> 
> echo output:
> 
> # pipe to sed simply for pretty nice indentation
> docker logs $cont | sed 's/^/\t/'
> 
> docker rm $cont &> /dev/null
> 
> # For ubuntu
> #!/bin/bash
> set -e
> 
> to=$1
> shift
> 
> cont=$(docker run -d "$@")
> code=$(timeout "$to" docker wait "$cont" || true)
> echo -n 'status: '
> if [ -z "$code" ]; then
> echo timeout
> else
> echo exited: $code
> fi
> 
> echo output:
> 
> # pipe to sed simply for pretty nice indentation
> docker logs $cont | sed 's/^/\t/'
> 
> docker rm $cont &> /dev/null


Adding the OS detect script in DockerTimeout.sh:
```
if [[ "$OSTYPE" == "darwin"* ]]; then
    code=$(gtimeout "$to" docker wait "$cont" || true)
else
    code=$(timeout "$to" docker wait "$cont" || true)
fi
```

ps: The `CoreUtils`'s install comman is:  `brew install coreutils`, it's coreutils NOT coreutil.
