### ISSUE TITLE
Docker Image is not generating 

### ISSUE THREAD

**Issue by SantoshKumar3295** [remoteinterview/compilebox#39]
compilebox/Setup/UpdateDocker.sh: line 3: Dockerfile: No such file or directory
Retrieving Installed Docker Images
REPOSITORY TAG IMAGE ID CREATED SIZE
None              None 57d2cfcccb1e 16 hours ago 1.586 GB
chug/ubuntu14.04x64 latest aaaa7bd9d11a 3 years ago 224.7

No Docker Image is generating i have tried the fresh install and checked the permission thing but still its not working.Please help

**Comment by CreateChen** [comment]
Hi @SantoshKumar3295 
How you fix this issue?
