### ISSUE TITLE
Install on Mac OSX

### ISSUE THREAD

**Issue by pvn-chi-ngo** [remoteinterview/compilebox#40]
Can I install on Mac OSX?
Because if I want to use Ubuntu/CentOS, I have to install Docker-in-Docker:
Docker image 1: Cent OS/Ubuntu
Docker image 2 (in 1): 'virtual machine'
Then I met many problems with this @@
Thanks you so much!

**Comment by chao00440** [comment]
did you figure out how do you install it on Mac?

**Comment by DoctorsInTech** [comment]
Did anybody figure this one out?
