### ISSUE TITLE
Install compilebox in docker container

### ISSUE THREAD

**Issue by pvn-chi-ngo** [remoteinterview/compilebox#41]
I install compilebox by this way:
- Create CentOS/Ubuntu image: only contains centos/ubunto + folder code
- Run into container and install in it. But when docker build 'virtual machine', I met many problems. I've solved a few. But now I'm stuck @@:
```
...
Step 28/35 : RUN apt-get install -y scala
...

...
Errors were encountered while processing:
 libpam-systemd:amd64
 policykit-1
 colord
 policykit-1-gnome
E: Sub-process /usr/bin/dpkg returned an error code (1)
```
Please help me to resolve this problem. Thank you so much!

**Comment by pvn-chi-ngo** [comment]
I've done it with Docker-in-Docker in 'sibling' style, without scalar language.

**Comment by saurabh1294** [comment]
Hi @pvn-chi-ngo ,

I am stuck at the same location. Please help. I need detailed steps for fixing this one. Can you mail me at saurabh.gattani@gmail.com ?
