### ISSUE TITLE
Is it possible to get pretified version, with chat and share URL

### ISSUE THREAD

**Issue by CrashyBang** [remoteinterview/compilebox#9]
I love this it is probably the coolest thing since sliced bread, however is it possible to get pretified version, with chat and share URL not to worried about the CSS but I love being able to use collaboratively.

**Comment by asadm** [comment]
We made: https://codepad.remoteinterview.io as a demo for compilebox.
It is exactly what you said.

If you want to make your own, Look into Firepad.

**Comment by CrashyBang** [comment]
So it is not possible to get the source code for https://codepad.remoteinterview.io, thank-you did you use firepad?

**Comment by asadm** [comment]
We haven't open sourced it yet. But yes you can quickly make one using Firepad + Compilebox.
